name: CI
on: 
  push:
    branches: [allure-setup] 
jobs:
  build:
    runs-on: ubuntu-latest

  strategy:
    matrix: 
      node-verison: [16.x]


    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: ${{matrix.node-version}}
            cashe: 'npm'
        - run: npm install
        - run: npm run build --if-present
        
        - name: Run the test
        - run: npm run wdio 
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs